language: python
python:
- '3.6'
before_install:
  - echo $settings_password | gpg --passphrase-fd 0 super_secret.txt.gpg
  - export MINICONDA=$HOME/miniconda
  - export PATH="$MINICONDA/bin:$PATH"
  - hash -r
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -f -p $MINICONDA
  - conda config --set always_yes yes
  - conda update conda
  - conda info -a
  - echo "Python version var"
  - echo $TRAVIS_PYTHON_VERSION
  - sed -i -E 's/(python=)(.*)/\1'$TRAVIS_PYTHON_VERSION'/' ./environment.yml
  - conda env create -n testenv -f environment.yml
  - conda install -c anaconda dnspython
  - source activate testenv
script:
- pytest --rootdir=tests/ -v
dd:
  secure: xny+yV89RUk6V8M6ieeFv4TH+si1P+woWvhKA2gCHnsE45GHl3nEAOJ2pCwMV5/SrTY+z/M1nYxmYHSJiFx1A7mipxAYEx1L6W6IgjO/7d0yTZz28QcHx1OZfWoND1njER3OMFeZ8UErbwGETPQP+n0Gn2/Y3DDH2zXGG6ocdHaCLv/yazYLlgB6DmK5dshyArxLlSJ/mSQ6GHy7qPZ3+ZGriU1g7QEvKSdiG+/LtqMQD3MQMMOKcm6WGeoJRcBzkUOW41zdOy1k7qKdMM4PtsdHy5Rd81AbEV4gho4aOVubHADV8Y9Tvy4FIrf7sHpjyMvYKSAdFivJHK9Xk5Qod0KE2Jp82BpNpGcxqDaOV1pCZzSZVZEw3Headm3uhXTAMNbkF1DUhjivhXLzfbwri8bt4XX8qHgl8CE9AP3JEk9/DBv6svUNeACzJxMenH3ZyTfI2qx0dvje2fxm+lYaiAMkQeF7mQ2+WIoKWHbv3PzvNwVhDh321eohV0LX+qByf4HAX5oO7B3MOqtAqNBMGTDtn0KiAIVniB55jdJH87FdchtAxt1aLs0yJY4oWlumqdXdO00w/9fisNvVDNTZCkNG7mI2DgGA00WIltjnqZa/LxIfdguPACldaqTltD6rGu92VSRrRPAmKr2OpRRmurpmn7iMIWu4xA3JDLy0xEE=
